// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpshttppwwynhgodmsos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwc2h0dHBwd3d5bmhnb2Rtc29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzA2NzUsImV4cCI6MjA2ODI0NjY3NX0.J8D1wEPuLyyjGZ0RfWe6jTM9mkcEyjqrTs5ZPYyefgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});